### ISSUE TITLE
Syntax EffMessagePlayers not optional word

### ISSUE THREAD

**Issue by AlexLew95** [TheLimeGlass/Skungee#45]
# Description:

A syntax in the doc is wrong (and maybe more, I didn't check all):
```regex
[skungee] (message|send|msg) %strings% to [(all [[of] the]|the)] bungee[[ ][cord]] players
```

# Problem:

This code will not work at all:
```vb
command b <text>:
	trigger:
		send "&bmessage &e%arg-1% &bsent !"
		send arg-1 to bungee players
```
But this will:
```vb
command b <text>:
	trigger:
		send "&bmessage &e%arg-1% &bsent !"
		send arg-1 to bungee all players
```

So the word ``all`` is not optional to send a message to all players.

**I think the problem comes from:** https://github.com/TheLimeGlass/Skungee/blob/master/src/main/java/me/limeglass/skungee/spigot/elements/effects/EffMessagePlayers.java

**Comment by TheLimeGlass** [comment]
`bungee all players` is improper grammar, this was discussed on the Skunity Discord, it's grabbing all the players on the Spigot server rather than all Bungeecord players.

The syntax are
```
(message|send|msg) %strings% to bungee[[ ]cord] [(player|uuid)[s]] %strings/players%

and

(message|send|msg) %strings% to [(all [[of] the]|the)] bungee[[ ][cord]] players
```
These are in place to avoid conflicting with Skript's `send message` effect.

You can edit the syntax in your syntax.yml if you really want to use the syntax in the way you are.
```
